settings:
  title: 'Rebirth Labs Status Page'
  url: 'rebirthlabs.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: rebirthlabs.io # unique identifier
    name: rebirthlabs.io
    description: 'Our Main Site' # default=empty
    url: 'https://rebirthlabs.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: rebirthmeta.gg
    name: rebirthmeta.gg
    description: 'Our Gaming arm main site'
    url: 'https://rebirthmeta.gg/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: cryptounicorns
    name: CryptoUnicorns Dashboard
    url: 'https://cryptounicorns.rebirthlabs.io/'
    method: GET
    expectStatus: 200
    
   - id: pegaxy
    name: Pegaxy Dashboard
    url: 'https://pegaxy.rebirthlabs.io/'
    method: GET
    expectStatus: 200
   
  - id: API
    name: API
    url: 'https://api.rebirthlabs.io/'
    method: GET
    expectStatus: 200
